caduNAES/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include ("paginas.urls")),
    path('', include ("cadastros.urls")),
    path('', include ("usuarios.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/urls.py
from django.urls import path
# Importar as views
from .views import IndexView, SobreView

urlpatterns = [
    # Criar urls para as views
    path("", IndexView.as_view(), name ="inicio"),
    path("sobre/", SobreView.as_view(), name ="sobre"),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User


class Cidade(models.Model):
    nome = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.nome}/{self.estado}"

class Pessoa(models.Model):
    nome_completo = models.CharField(max_length=150)
    nascimento = models.DateField(verbose_name="data de nascimento")
    cpf = models.CharField(max_length=14, verbose_name="cpf", unique=True)
    email = models.EmailField(max_length=120, blank=True, null=True)
    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='fotos/', blank=True, null=True)

    def __str__(self):
        return f"{self.nome_completo} {self.cpf}"

class Apartamento(models.Model):
    numero = models.IntegerField()
    bloco = models.CharField(max_length=10)

    def __str__(self):
        return f"Apto {self.numero}, Bloco {self.bloco}"

class Carro(models.Model):
    placa = models.CharField(max_length=10)
    modelo = models.CharField(max_length=50)
    cor = models.CharField(max_length=20)
    apartamento = models.ForeignKey(Apartamento, on_delete=models.CASCADE, related_name="carros")

    def __str__(self):
        return f"{self.modelo} ({self.placa})"

class Morador(Pessoa):
    apartamento = models.OneToOneField(Apartamento, on_delete=models.CASCADE, related_name="morador")
    possui_animais = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.nome_completo} - Apto {self.apartamento.numero}, Bloco {self.apartamento.bloco}"

class Visita(models.Model):
    pessoa_visita = models.ForeignKey(Pessoa, on_delete=models.CASCADE, related_name='visitas_feitas')
    pessoa_visitada = models.ForeignKey(Morador, on_delete=models.CASCADE, related_name='visitas_recebidas')
    motivo = models.CharField(max_length=255)
    data_hora_entrada = models.DateTimeField()
    data_hora_saida = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Visitante {self.pessoa_visita.nome_completo} em Apto {self.pessoa_visitada.apartamento.numero}, {self.pessoa_visitada.nome_completo}, Bloco {self.pessoa_visitada.apartamento.bloco} - Entrada: {self.data_hora_entrada.strftime('%d/%m/%Y %H:%M')}"

class Porteiro(models.Model):
    nome = models.CharField(max_length=150)
    turno = models.CharField(max_length=50)

    def __str__(self):
        return f"Porteiro {self.nome} - Turno {self.turno}"

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Perfil(models.Model):
    nome_completo = models.CharField(max_length=255, null=True)
    cpf = models.CharField(max_length=14, null=True, verbose_name='CPF')
    telefone = models.CharField(max_length=16, null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UsuarioForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        e = self.cleaned_data['email']
        if User.objects.filter(email=e).exists():
            raise forms.ValidationError("O e-mail {} já está cadastrado.".format(e))
        return e

paginas/views.py
from django.views.generic import TemplateView

#criar uma view para pagina inicial
# com herança para a classe TemplateView
# Create your views here.

class IndexView (TemplateView):
    template_name ="paginas/index.html"

class SobreView(TemplateView):
    template_name = "paginas/sobre.html"

class LoginView(TemplateView):
    template_name = "paginas/login.html"

paginas/templates/paginas/index.html
{% extends "paginas/modelo.html" %}

{% load static %}

paginas/templates/paginas/index2.html
{% extends 'paginas/modelo-ifpr.html' %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
{% if user.perfil.nome_completo%}
Bem vindo ao sistema {{user.perfil.nome_completo}}
{% else %}
Você precisa completar seu cadastro. Acesse os <a href="{% url 'atualizar-dados' %}">seus dados</a> para atualizar.
{% endif %}
 
{% endblock %}

paginas/templates/paginas/modelo.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Caduzim</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script src="{% static 'js/scripts.js' %}"></script>

    <link href="https://cdn.datatables.net/v/bs5/dt-2.1.7/datatables.min.css" rel="stylesheet">

</head>


<body>

    <div class="container">
        {% block navegacao %}
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'inicio' %}">Cadu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav me-auto"> <!-- Usar 'me-auto' para alinhar à esquerda -->
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="cadastroDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Cadastros de itens
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="cadastroDropdown">
                                <li><a class="dropdown-item" href="{% url 'list-cidade' %}">Cidades</a></li>
                                <li><a class="dropdown-item" href="{% url 'list-pessoa' %}">Pessoas</a></li>
                                <li><a class="dropdown-item" href="{% url 'list-carro' %}">Carros</a></li>
                                <li><a class="dropdown-item" href="{% url 'list-morador' %}">Moradores</a></li>
                                <li><a class="dropdown-item" href="{% url 'list-porteiro' %}">Porteiros</a></li>
                                <li><a class="dropdown-item" href="{% url 'list-visita' %}">Visitas</a></li>
                                <li><a class="dropdown-item" href="{% url 'list-apartamento' %}">Apartamentos</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ms-auto"> <!-- Usar 'ms-auto' para alinhar à direita -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'sobre' %}">Sobre</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="usuarioDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="usuarioDropdown">
                                <li><a class="dropdown-item" href="{% url 'atualizar-dados' %}">Meus dados</a></li>
                                <li><form method="post" action="{% url 'logout' %}" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item" style="background: none; border: none; padding: 0; cursor: pointer;">Sair</button>
                                    </form>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Entrar</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'registrar' %}">Cadastrar</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% endblock %}
        
    </div>

    {% block header %}
    <header class="masthead text-center text-white">
        <div class="masthead-content">
            <div class="container px-5">
                <h1 class="masthead-heading mb-0">O melhor site</h1>
                <h2 class="masthead-subheading mb-0">do IFPR</h2>
                <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Leia mais</a>
            </div>
        </div>
        <div class="bg-circle-1 bg-circle"></div>
        <div class="bg-circle-2 bg-circle"></div>
        <div class="bg-circle-3 bg-circle"></div>
        <div class="bg-circle-4 bg-circle"></div>
    </header>
    {% endblock %}

    <section id="scroll">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg py-4">
                {% block content %}

                {% endblock %}
            </div>
            <!-- <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src= "{% static 'assets/img/01.jpg' %}" alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                        <h2 class="display-4">For those about to rock...</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                </div>
            </div> -->
        </div>
    </div>
    </section>

    <!-- Content section 2-->
    <!-- <section>
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6">
                    <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="..." /></div>
                </div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <h2 class="display-4">We salute you!</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                    </div>
                </div>
            </div>
        </div>
    </section> -->
    <!-- Content section 3-->
    <!-- <section>
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}" alt="..." /></div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <h2 class="display-4">Let there be rock!</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                    </div>
                </div>
            </div>
        </div>
    </section> -->
    

    {% block rodape %}  
    <footer class="py-5 bg-black">
        <div class="container px-5">
          <p class="m-0 text-center text-white small">Copyright &copy; CADUHD4 2024</p>
        </div>
      </footer>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="https://cdn.datatables.net/v/bs5/dt-2.1.7/datatables.min.js"></script>
    {% block scripts %}
    
    
    {% endblock %}


    </body>
</html>

paginas/templates/paginas/register.html
{% extends "paginas/modelo.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block header %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Criar uma conta</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block">Criar conta</button>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    <div class="small"><a href="{% url 'login' %}">Já tem uma conta? Entre aqui</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_telefone').mask('(00) 00000-0000');
        $('#id_cpf').mask('000.000.000-00');
        $('#id_data_hora_entrada').mask('00/00/0000 00:00');
        $('#id_data_hora_saida').mask('00/00/0000 00:00');
        $('#id_nascimento').mask('00/00/0000');
        $('#id_email').mask('A', {
            translation: {
                'A': {pattern: /[\w@\-.+]/, recursive: true}
            }
        });
    });
</script>
{% endblock %}

paginas/templates/paginas/sobre.html
{% extends "modelo.html" %}
{% load static %}

{% block content %}
    <div class="container py-5">
        <h1 class="text-center">Sobre o projeto</h1>
        <p class="text-center">Meu nome é caduHD4 e o meu sistema ainda num funciona!</p>
        <p class="text-center">Contato: 20210000709@estudantes.ifpr.edu.br</p>
        <div class="row">
            <div class="col-md-6 text-center">
                <img src="{% static 'img/casos_de_uso1.png' %}" alt="Casos de Uso 1" class="img-fluid rounded mb-4">
                <img src="{% static 'img/casos_de_uso2.png' %}" alt="Casos de Uso 2" class="img-fluid rounded mb-4">
                <img src="{% static 'img/casos_de_uso3.png' %}" alt="Casos de Uso 3" class="img-fluid rounded">
                <p>Casos de Uso</p>
            </div>
            <div class="col-md-6 text-center">
                <img src="{% static 'img/diagrama_de_classes.jpeg' %}" alt="Diagrama de Classe" class="img-fluid rounded">
                <p>Diagrama de Classe</p>
            </div>
        </div>
    </div>
{% endblock %}